services:
  translator:
    image: ghcr.io/riccardobl/openagents-translator-node:master
    environment:
      - NOSTR_CONNECT_GRPC_BINDING_ADDRESS=grpc
      - NOSTR_CONNECT_GRPC_BINDING_PORT=5000
      - DEVICE=-1 
    networks:
      openagents-node-network:
        external: true

