services:
  grpc:
    image: ghcr.io/riccardobl/openagents-grpc:master
    networks:
      - openagents-node-network

  translate:
    image: ghcr.io/riccardobl/openagents-translate:master-cuda
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NOSTR_CONNECT_GRPC_BINDING_ADDRESS=grpc
      - NOSTR_CONNECT_GRPC_BINDING_PORT=5000
      - DEVICE=0
    networks:
      - openagents-node-network

networks:
  openagents-node-network:
    driver: bridge